---
extends: default
ignore: |
  .git/
  .venv/
  node_modules/
  *.tmp.yaml
  docker-compose.*
rules:
  line-length: disable
  brackets:
    min-spaces-inside: 1
    max-spaces-inside: 2
  truthy: disable
